### ISSUE TITLE
Persiapan Menggunakan Github.com dan Github Desktop

### ISSUE THREAD

**Issue by efanzakie85** [efanzakie85/TestGithub#1]
Berikut langkah-langkah persiapan menggunakan github:
- buat akun di github.com
- download github desktop dan instal dikomputer lokal
- download editor Visual Studio Code dan instal di komputer lokal

**Comment by aliaszakie** [comment]
pak, bagaimana cara buat akun di github?

**Comment by efanzakie85** [comment]
tonton video ini https://www.youtube.com/watch?v=Q3Id0DgcrXY&list=PLFIM0718LjIVknj6sgsSceMqlq242-jNf&index=2

**Comment by efanzakie85** [comment]
> pak, bagaimana cara buat akun di github?

tonton video ini : https://www.youtube.com/watch?v=Q3Id0DgcrXY&list=PLFIM0718LjIVknj6sgsSceMqlq242-jNf&index=2

**Comment by aliaszakie** [comment]
halo pak...
